<?php

return [
  'code' => 'chr_rkbmn',
  'name' => 'CHR RKBMN',
  'version' => 1,
  'renderer' => 'dynamic',
  'sections' => [
    [
      'key' => 'identitas',
      'title' => 'Identitas Dokumen',
      'fields' => [
        ['key' => 'judul_dokumen', 'label' => 'Judul Dokumen', 'type' => 'text', 'width' => 6],
        ['key' => 'subjudul', 'label' => 'Subjudul', 'type' => 'text', 'width' => 6],
        ['key' => 'entitas', 'label' => 'Entitas', 'type' => 'text', 'width' => 6],
        ['key' => 'unit_yang_direviu', 'label' => 'Unit/Satker yang Direviu', 'type' => 'text', 'width' => 6],
        ['key' => 'nomor_chr', 'label' => 'Nomor CHR', 'type' => 'text', 'width' => 4],
        ['key' => 'tanggal_chr', 'label' => 'Tanggal CHR', 'type' => 'date', 'width' => 4],
        ['key' => 'tahun_anggaran', 'label' => 'Tahun Anggaran RKBMN', 'type' => 'text', 'width' => 4],
        ['key' => 'nomor_surat_tugas', 'label' => 'Nomor Surat Tugas', 'type' => 'text', 'width' => 6],
        ['key' => 'tanggal_surat_tugas', 'label' => 'Tanggal Surat Tugas', 'type' => 'date', 'width' => 6],
      ],
    ],
    [
      'key' => 'penyusun',
      'title' => 'Penyusun Dokumen',
      'fields' => [
        ['key' => 'disusun_oleh', 'label' => 'Disusun oleh', 'type' => 'text', 'width' => 4],
        ['key' => 'tanggal_disusun', 'label' => 'Tanggal Disusun', 'type' => 'date', 'width' => 4],
        ['key' => 'direviu_oleh', 'label' => 'Direviu oleh', 'type' => 'text', 'width' => 4],
        ['key' => 'tanggal_direviu', 'label' => 'Tanggal Direviu', 'type' => 'date', 'width' => 4],
        ['key' => 'disetujui_oleh', 'label' => 'Disetujui oleh', 'type' => 'text', 'width' => 4],
        ['key' => 'tanggal_disetujui', 'label' => 'Tanggal Disetujui', 'type' => 'date', 'width' => 4],
      ],
    ],
    [
      'key' => 'uraian_reviu',
      'title' => 'Uraian Catatan Hasil Reviu',
      'fields' => [
        ['key' => 'dasar_reviu', 'label' => 'Dasar Pelaksanaan Reviu', 'type' => 'textarea', 'rows' => 4],
        ['key' => 'batas_tanggung_jawab', 'label' => 'Batas Tanggung Jawab Reviu', 'type' => 'textarea', 'rows' => 4],
      ],
    ],
    [
      'key' => 'kelengkapan_dokumen',
      'title' => 'Kelengkapan dan Kesesuaian Dokumen Pendukung',
      'fields' => [
        [
          'key' => 'checklist',
          'label' => 'Checklist Dokumen RKBMN',
          'type' => 'repeater',
          'min_rows' => 8,
          'columns' => [
            ['key' => 'kategori', 'label' => 'Kategori', 'type' => 'select', 'options' => ['Kelengkapan Dokumen', 'Legalitas Dokumen', 'Kesesuaian Format Dokumen RKBMN', 'Lainnya']],
            ['key' => 'dokumen', 'label' => 'Dokumen/Pertanyaan Reviu', 'type' => 'textarea'],
            ['key' => 'hasil', 'label' => 'Hasil', 'type' => 'select', 'options' => ['Ada', 'Tidak', 'Ya', 'Tidak Relevan']],
            ['key' => 'keterangan', 'label' => 'Keterangan', 'type' => 'textarea'],
          ],
        ],
      ],
    ],
    [
      'key' => 'kesesuaian_program',
      'title' => 'Kesesuaian Program, Kegiatan, dan Keluaran BMN',
      'fields' => [
        ['key' => 'uraian', 'label' => 'Uraian Hasil Reviu', 'type' => 'textarea', 'rows' => 5],
        ['key' => 'kesimpulan', 'label' => 'Kesimpulan', 'type' => 'textarea', 'rows' => 4],
      ],
    ],
    [
      'key' => 'rincian_pengadaan',
      'title' => 'Rincian Pengadaan BMN',
      'fields' => [
        [
          'key' => 'bangunan_tanah',
          'label' => 'Pengadaan Bangunan/Tanah/Rumah Negara',
          'type' => 'repeater',
          'min_rows' => 1,
          'columns' => [
            ['key' => 'unit_satker', 'label' => 'Unit Satker/Kode Satker', 'type' => 'text'],
            ['key' => 'kode_barang', 'label' => 'Kode Barang', 'type' => 'text'],
            ['key' => 'uraian_barang', 'label' => 'Uraian Barang', 'type' => 'textarea'],
            ['key' => 'jumlah_usulan', 'label' => 'Jumlah Usulan', 'type' => 'number'],
            ['key' => 'kebutuhan_riil', 'label' => 'Kebutuhan Riil', 'type' => 'number'],
            ['key' => 'hasil_pembahasan', 'label' => 'Hasil Pembahasan Bidang PU', 'type' => 'select', 'options' => ['Ada', 'Tidak Ada', 'Tidak Relevan']],
            ['key' => 'jumlah_disetujui', 'label' => 'Jumlah Disetujui APIP', 'type' => 'number'],
            ['key' => 'keterangan', 'label' => 'Keterangan', 'type' => 'textarea'],
          ],
        ],
        [
          'key' => 'aadb',
          'label' => 'Pengadaan AADB/BMN Selain Tanah Bangunan',
          'type' => 'repeater',
          'min_rows' => 1,
          'columns' => [
            ['key' => 'unit_satker', 'label' => 'Unit Satker', 'type' => 'text'],
            ['key' => 'kode_barang', 'label' => 'Kode Barang', 'type' => 'text'],
            ['key' => 'uraian_barang', 'label' => 'Uraian Barang', 'type' => 'textarea'],
            ['key' => 'jumlah_usulan', 'label' => 'Jumlah Usulan', 'type' => 'number'],
            ['key' => 'sbsk', 'label' => 'SBSK', 'type' => 'number'],
            ['key' => 'existing_rencana', 'label' => 'Existing dan Rencana Pengadaan', 'type' => 'number'],
            ['key' => 'rencana_penghapusan', 'label' => 'Rencana Penghapusan/Penghentian', 'type' => 'number'],
            ['key' => 'kebutuhan_riil', 'label' => 'Kebutuhan Riil', 'type' => 'number'],
            ['key' => 'terkoreksi_apip', 'label' => 'Terkoreksi APIP', 'type' => 'number'],
            ['key' => 'keterangan', 'label' => 'Keterangan', 'type' => 'textarea'],
          ],
        ],
      ],
    ],
    [
      'key' => 'catatan_rekomendasi',
      'title' => 'Catatan dan Rekomendasi',
      'fields' => [
        ['key' => 'koreksi_hasil_reviu', 'label' => 'Koreksi Hasil Reviu', 'type' => 'textarea', 'rows' => 5],
        ['key' => 'hal_perlu_diungkap', 'label' => 'Hal yang Perlu Diungkap', 'type' => 'textarea', 'rows' => 5],
        ['key' => 'rekomendasi', 'label' => 'Rekomendasi', 'type' => 'textarea', 'rows' => 5],
        ['key' => 'kesimpulan', 'label' => 'Kesimpulan', 'type' => 'textarea', 'rows' => 5],
      ],
    ],
    [
      'key' => 'pengesahan',
      'title' => 'Pengesahan',
      'fields' => [
        ['key' => 'pejabat_menyetujui', 'label' => 'Pejabat Menyetujui', 'type' => 'signature'],
        ['key' => 'ketua_tim', 'label' => 'Ketua Tim', 'type' => 'signature'],
        ['key' => 'anggota_tim', 'label' => 'Anggota Tim', 'type' => 'repeater', 'min_rows' => 1, 'columns' => [
          ['key' => 'user_id', 'label' => 'Pegawai', 'type' => 'text'],
          ['key' => 'nama', 'label' => 'Nama', 'type' => 'text'],
          ['key' => 'nip', 'label' => 'NIP', 'type' => 'text'],
          ['key' => 'jabatan', 'label' => 'Jabatan', 'type' => 'text'],
          ['key' => 'unit_id', 'label' => 'Unit ID', 'type' => 'text'],
          ['key' => 'unit', 'label' => 'Unit Kerja', 'type' => 'text'],
          ['key' => 'tanggal', 'label' => 'Tanggal', 'type' => 'date'],
          ['key' => 'signature', 'label' => 'Tanda Tangan', 'type' => 'signature_data'],
        ]],
      ],
    ],
  ],
  'export_sections' => [
    ['key' => 'identitas', 'title' => 'Identitas Dokumen', 'fields' => ['entitas', 'unit_yang_direviu', 'nomor_chr', 'tanggal_chr', 'tahun_anggaran', 'nomor_surat_tugas', 'tanggal_surat_tugas']],
    ['key' => 'penyusun', 'title' => 'Penyusun Dokumen'],
    ['key' => 'uraian_reviu', 'title' => 'Uraian Catatan Hasil Reviu'],
    ['key' => 'kelengkapan_dokumen', 'title' => 'Kelengkapan dan Kesesuaian Dokumen Pendukung', 'block_repeaters' => true],
    ['key' => 'kesesuaian_program', 'title' => 'Kesesuaian Program, Kegiatan, dan Keluaran BMN'],
    ['key' => 'rincian_pengadaan', 'title' => 'Rincian Pengadaan BMN', 'block_repeaters' => true],
    ['key' => 'catatan_rekomendasi', 'title' => 'Koreksi Hasil Reviu', 'only' => ['koreksi_hasil_reviu']],
    ['key' => 'catatan_rekomendasi', 'title' => 'Hal yang Perlu Diungkap', 'only' => ['hal_perlu_diungkap']],
    ['key' => 'catatan_rekomendasi', 'title' => 'Rekomendasi', 'only' => ['rekomendasi']],
    ['key' => 'catatan_rekomendasi', 'title' => 'Kesimpulan', 'only' => ['kesimpulan']],
    ['key' => 'pengesahan', 'title' => 'Pengesahan'],
  ],
];
