<?php

return [
  'code' => 'chr_rkakl',
  'name' => 'CHR RKA/RKAKL',
  'version' => 2,
  'renderer' => 'dynamic',
  'sections' => [
    [
      'key' => 'identitas',
      'title' => 'Identitas Dokumen',
      'fields' => [
        ['key' => 'header_baris_1', 'label' => 'Header Baris 1', 'type' => 'text', 'width' => 6],
        ['key' => 'header_baris_2', 'label' => 'Header Baris 2', 'type' => 'text', 'width' => 6],
        ['key' => 'judul_dokumen', 'label' => 'Judul Dokumen', 'type' => 'text', 'width' => 6],
        ['key' => 'subjudul', 'label' => 'Subjudul', 'type' => 'text', 'width' => 6],
        ['key' => 'kementerian_lembaga', 'label' => 'Kementerian Negara/Lembaga', 'type' => 'text', 'width' => 6],
        ['key' => 'apip', 'label' => 'APIP', 'type' => 'text', 'width' => 6],
        ['key' => 'eselon_unit', 'label' => 'RKA-K/L Eselon I / Unit', 'type' => 'text', 'width' => 6],
        ['key' => 'unit_kerja', 'label' => 'Unit Kerja', 'type' => 'text', 'width' => 6],
        ['key' => 'tahun_anggaran', 'label' => 'Tahun Anggaran', 'type' => 'text', 'width' => 4],
        ['key' => 'periode', 'label' => 'Periode Reviu', 'type' => 'text', 'width' => 4],
        ['key' => 'nomor_chr', 'label' => 'Nomor CHR', 'type' => 'text', 'width' => 4],
        ['key' => 'tanggal_chr', 'label' => 'Tanggal CHR', 'type' => 'date', 'width' => 4],
        ['key' => 'nomor_surat_tugas', 'label' => 'Nomor Surat Tugas', 'type' => 'text', 'width' => 4],
        ['key' => 'tanggal_surat_tugas', 'label' => 'Tanggal Surat Tugas', 'type' => 'date', 'width' => 4],
      ],
    ],
    [
      'key' => 'penyusun',
      'title' => 'Penyusun Dokumen',
      'fields' => [
        ['key' => 'disusun_oleh', 'label' => 'Disusun Oleh', 'type' => 'text', 'width' => 4],
        ['key' => 'tanggal_disusun', 'label' => 'Tanggal Disusun', 'type' => 'date', 'width' => 4],
        ['key' => 'diteliti_oleh', 'label' => 'Diteliti Oleh', 'type' => 'text', 'width' => 4],
        ['key' => 'tanggal_diteliti', 'label' => 'Tanggal Diteliti', 'type' => 'date', 'width' => 4],
        ['key' => 'disetujui_oleh', 'label' => 'Disetujui Oleh', 'type' => 'text', 'width' => 4],
        ['key' => 'tanggal_disetujui', 'label' => 'Tanggal Disetujui', 'type' => 'date', 'width' => 4],
      ],
    ],
    [
      'key' => 'uraian_penugasan',
      'title' => 'Uraian Catatan Hasil Reviu',
      'fields' => [
        ['key' => 'dasar_surat_tugas', 'label' => 'Dasar Surat Tugas', 'type' => 'textarea', 'rows' => 3],
        ['key' => 'objek_reviu', 'label' => 'Objek Reviu RKA-K/L', 'type' => 'textarea', 'rows' => 3],
        ['key' => 'tahun_anggaran_reviu', 'label' => 'Tahun Anggaran yang Direviu', 'type' => 'text', 'width' => 6],
        ['key' => 'ringkasan_pengantar', 'label' => 'Ringkasan Pengantar', 'type' => 'textarea', 'rows' => 4],
      ],
    ],
    [
      'key' => 'data_umum',
      'title' => 'Data Umum',
      'fields' => [
        ['key' => 'pagu_indikatif_nomor_dasar', 'label' => 'Dasar Pagu Indikatif', 'type' => 'text', 'width' => 6],
        ['key' => 'pagu_indikatif_total', 'label' => 'Total Pagu Indikatif', 'type' => 'text', 'width' => 6],
        [
          'key' => 'pagu_indikatif_rincian',
          'label' => 'Rincian Pagu Indikatif per Sumber Dana dan Jenis Belanja',
          'type' => 'repeater',
          'min_rows' => 1,
          'columns' => [
            ['key' => 'sumber_dana', 'label' => 'Sumber Dana', 'type' => 'select', 'options' => ['Rupiah Murni', 'PNBP', 'BLU', 'PLN', 'HLN', 'PDN', 'SBSN', 'Lainnya']],
            ['key' => 'belanja_pegawai', 'label' => 'Belanja Pegawai', 'type' => 'text'],
            ['key' => 'belanja_barang', 'label' => 'Belanja Barang', 'type' => 'text'],
            ['key' => 'belanja_modal', 'label' => 'Belanja Modal', 'type' => 'text'],
            ['key' => 'jumlah', 'label' => 'Jumlah', 'type' => 'text'],
            ['key' => 'catatan', 'label' => 'Catatan', 'type' => 'textarea'],
          ],
        ],
        ['key' => 'pagu_anggaran_nomor_dasar', 'label' => 'Dasar Pagu Anggaran', 'type' => 'text', 'width' => 6],
        ['key' => 'pagu_anggaran_total', 'label' => 'Total Pagu Anggaran', 'type' => 'text', 'width' => 6],
        [
          'key' => 'pagu_anggaran_rincian',
          'label' => 'Rincian Pagu Anggaran per Sumber Dana dan Jenis Belanja',
          'type' => 'repeater',
          'min_rows' => 1,
          'columns' => [
            ['key' => 'sumber_dana', 'label' => 'Sumber Dana', 'type' => 'select', 'options' => ['Rupiah Murni', 'PNBP', 'BLU', 'PLN', 'HLN', 'PDN', 'SBSN', 'Lainnya']],
            ['key' => 'belanja_pegawai', 'label' => 'Belanja Pegawai', 'type' => 'text'],
            ['key' => 'belanja_barang', 'label' => 'Belanja Barang', 'type' => 'text'],
            ['key' => 'belanja_modal', 'label' => 'Belanja Modal', 'type' => 'text'],
            ['key' => 'jumlah', 'label' => 'Jumlah', 'type' => 'text'],
            ['key' => 'catatan', 'label' => 'Catatan', 'type' => 'textarea'],
          ],
        ],
      ],
    ],
    [
      'key' => 'pemeriksaan',
      'title' => 'Pemeriksaan RKA-K/L',
      'fields' => [
        [
          'key' => 'aspek_reviu',
          'label' => 'Aspek Reviu',
          'type' => 'repeater',
          'min_rows' => 6,
          'columns' => [
            ['key' => 'aspek', 'label' => 'Aspek Pemeriksaan', 'type' => 'select', 'options' => [
              'Kesesuaian dengan RKP dan Renja-K/L',
              'Kesesuaian dengan Pagu Anggaran',
              'Kesesuaian dengan Alokasi Anggaran',
              'Kelengkapan Dokumen Pendukung',
              'Kesesuaian Biaya Pemeliharaan',
              'Kesesuaian Biaya Pengadaan',
              'Lainnya',
            ]],
            ['key' => 'uraian_hasil', 'label' => 'Uraian Hasil Reviu', 'type' => 'textarea'],
            ['key' => 'kriteria', 'label' => 'Kriteria', 'type' => 'textarea'],
            ['key' => 'status_kesesuaian', 'label' => 'Status', 'type' => 'select', 'options' => ['Sesuai', 'Belum Sesuai', 'Tidak Sesuai', 'Telah Lengkap', 'Belum Lengkap', 'Tidak Relevan']],
            ['key' => 'kesimpulan', 'label' => 'Kesimpulan', 'type' => 'textarea'],
          ],
        ],
      ],
    ],
    [
      'key' => 'koreksi_rekomendasi',
      'title' => 'Koreksi, Rekomendasi, dan Kesimpulan',
      'fields' => [
        ['key' => 'koreksi_belum_dilakukan', 'label' => 'Koreksi/Perbaikan yang Belum Dilakukan atau Tidak Disetujui', 'type' => 'textarea', 'rows' => 5],
        ['key' => 'rekomendasi', 'label' => 'Rekomendasi', 'type' => 'textarea', 'rows' => 5],
        ['key' => 'kesimpulan_umum', 'label' => 'Kesimpulan Umum', 'type' => 'textarea', 'rows' => 5],
      ],
    ],
    [
      'key' => 'pengesahan',
      'title' => 'Pengesahan',
      'fields' => [
        ['key' => 'pejabat_menyetujui', 'label' => 'Pejabat Menyetujui', 'type' => 'signature'],
        ['key' => 'ketua_tim', 'label' => 'Ketua Tim', 'type' => 'signature'],
        ['key' => 'anggota_tim', 'label' => 'Anggota Tim', 'type' => 'repeater', 'min_rows' => 1, 'columns' => [
          ['key' => 'user_id', 'label' => 'Pegawai', 'type' => 'text'],
          ['key' => 'nama', 'label' => 'Nama', 'type' => 'text'],
          ['key' => 'nip', 'label' => 'NIP', 'type' => 'text'],
          ['key' => 'jabatan', 'label' => 'Jabatan', 'type' => 'text'],
          ['key' => 'unit_id', 'label' => 'Unit ID', 'type' => 'text'],
          ['key' => 'unit', 'label' => 'Unit Kerja', 'type' => 'text'],
          ['key' => 'tanggal', 'label' => 'Tanggal', 'type' => 'date'],
          ['key' => 'signature', 'label' => 'Tanda Tangan', 'type' => 'signature_data'],
        ]],
      ],
    ],
  ],
  'export_sections' => [
    ['key' => 'identitas', 'title' => 'Identitas Dokumen', 'fields' => ['kementerian_lembaga', 'apip', 'eselon_unit', 'unit_kerja', 'tahun_anggaran', 'nomor_chr', 'tanggal_chr', 'nomor_surat_tugas', 'tanggal_surat_tugas']],
    ['key' => 'penyusun', 'title' => 'Penyusun Dokumen'],
    ['key' => 'uraian_penugasan', 'title' => 'Uraian Catatan Hasil Reviu'],
    ['key' => 'data_umum', 'title' => 'Data Umum', 'block_repeaters' => true],
    ['key' => 'pemeriksaan', 'title' => 'Pemeriksaan RKA-K/L', 'block_repeaters' => true],
    ['key' => 'koreksi_rekomendasi', 'title' => 'Koreksi/Perbaikan dan Rekomendasi'],
    ['key' => 'pengesahan', 'title' => 'Pengesahan'],
  ],
];
