autoindex off;

location ~ /\.(?!well-known).* { deny all; }
location ~* (\.DS_Store|^\._) { deny all; }

location ~* \.(sql|log|bak|zip|rar|7z|tar|gz|md)$ { deny all; }

location ^~ /db/ { deny all; }
location ^~ /vendor/ { deny all; }
location ^~ /config/ { deny all; }
location ^~ /deploy/ { deny all; }
location ^~ /cron/ { deny all; }
location ^~ /storage_sql_backup/ { deny all; }
location ^~ /storage/ { deny all; }
location ^~ /tools/ {
  allow 127.0.0.1;
  allow ::1;
  deny all;
}

location = /db.php { deny all; }
location = /config_mail.php { deny all; }
location ~* _helpers\.php$ { deny all; }

location ^~ /upload/ { return 403; }
location ^~ /uploads/ { return 403; }

